version: '3'
services:
  todo-app:
    build: ./todo-app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  order-app:
    build: ./order-app
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
